pipelines:
  branches:
    master:
      - step:
          script:
            - echo "only on master"
            - pipe: atlassian/ftp-deploy:0.3.2
              variables:
                USER: '$FTP_USER'
                PASSWORD: '$FTP_PASSWORD'
                SERVER: '$FTP_HOST'
                REMOTE_PATH: '.'
                DEBUG: 'true'