# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: node:10.15.3

pipelines:
  branches:
    master:
      - step:
          script:
            - echo "only on master"
            - git ftp push -u "nicolazunino" -p "biccigetga26" ftp://ftp.nicolazunino.altervista.org --all.'
